<a href="https://colab.research.google.com/github/FasterThanAi/ML_Projects/blob/main/NLP_ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df=pd.read_csv('train.txt',sep=';', header=None,names=['text','emotion'])

In [45]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [46]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [47]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

create  6 dict. for each emotion

In [48]:
unique_emotion=df['emotion'].unique()

In [49]:
emotion_num={}
i=0
for emo in unique_emotion:
  emotion_num[emo]=i;
  i+=1;
df['emotion']=df['emotion'].map(emotion_num)

In [38]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

lower case conversion

In [50]:
df['text']=df['text'].apply(lambda x:x.lower())

In [51]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

removing punctutation

In [52]:
import string

def remove_punch(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [53]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [54]:
df['text']=df['text'].apply(remove_punch)

In [55]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

remove numbers

In [56]:
def remove_num(txt):
  new =""
  for i in txt:
    if not i.isdigit():
      new+=i
  return new
df['text']=df['text'].apply(remove_num)

In [57]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

remove url and links . by removing https , /

remove emoji and special char

In [58]:
def remove_emoji(txt):
  new=""
  for i in txt:
    if i.isascii():
      new+=i
  return new

df['text']=df['text'].apply(remove_emoji)

In [59]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

remove stop words
NLTK : lib
spacy is also same

In [60]:
import nltk

corpus: collection of text . like a dataset of text
eg : folder of 10K twitter msg
Token:  each individual word or symbol in the text.

In [61]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [62]:
nltk.download('punkt') # it is lib that tokenize
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [63]:
stop_words=set(stopwords.words('english'))

In [64]:
len(stop_words)

198

each sentence me se stop word removal

In [65]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [71]:
def remove(txt):
  #words=word_tokenize(txt)
  words=txt.split()
  cleaned=[]
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [72]:
df['text']=df['text'].apply(remove)

In [74]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

now we done text preprocessing

NOW we move towards vectorization

In [83]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [85]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [86]:
X_train.shape

(12800,)

In [88]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

text vectorization

In [107]:
from sklearn.feature_extraction.text import CountVectorizer #BOW
from sklearn.feature_extraction.text import TfidfVectorizer #TF IDF

bow_vectorizer = CountVectorizer()
# tfidf_vectorizer = TfidfVectorizer()

In [108]:
x_train_bow=bow_vectorizer.fit_transform(X_train)
# x_train_tfidf=tfidf_vectorizer.fit_transform(X_train)

In [109]:
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116059 stored elements and shape (12800, 13361)>

In [110]:
x_test_bow=bow_vectorizer.transform(X_test)
# x_test_tfidf=tfidf_vectorizer.transform(X_test)

naive bayes and logistic regresion

In [111]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

In [112]:
nb_model=MultinomialNB()

In [113]:
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [115]:
predict_nb=nb_model.predict(x_test_bow)
print(accuracy_score(y_test,predict_nb))
# print(classification_report(y_test,predict_nb)

0.768125

In [116]:
predict_nb

array([0, 5, 0, ..., 5, 5, 0])

TF IDF

In [118]:
tfidf_vectorizer = TfidfVectorizer()
x_train_tfidf=tfidf_vectorizer.fit_transform(X_train)
x_test_tfidf=tfidf_vectorizer.transform(X_test)

nb2_model=MultinomialNB()
nb2_model.fit(x_train_tfidf,y_train)

MultinomialNB()

In [119]:
y_pred=nb2_model.predict(x_test_tfidf)
print(accuracy_score(y_test,y_pred))

0.6609375

Logistic reg on TFIDF

In [120]:
from sklearn.linear_model import LogisticRegression

In [121]:
logis_model=LogisticRegression(max_iter=1000)
logis_model.fit(x_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [122]:
log_pred=logis_model.predict(x_test_tfidf)
print(accuracy_score(y_test,log_pred))

0.8628125

bag of words

In [80]:
from sklearn.feature_extraction.text import CountVectorizer

documents=[
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]
vectorizer=CountVectorizer(ngram_range=(2,2)) #bigram

X=vectorizer.fit_transform(documents)
print("Vocabulary",vectorizer.get_feature_names_out())
print("\nBOW Matrix\n",X.toarray())

Vocabulary ['is great' 'is the' 'love pasta' 'love pizza' 'pasta is' 'pizza is'
 'the best']

BOW Matrix
 [[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer
documents=[
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]
vectorizer=TfidfVectorizer()

X=vectorizer.fit_transform(documents)
print("Vocabulary",vectorizer.get_feature_names_out())
print("\nBOW Matrix\n",X.toarray())

Vocabulary ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

BOW Matrix
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]